### ISSUE TITLE
fails to compile with OpenSSL 1.1.0

### ISSUE THREAD

**Issue by anarcat** [atheme/atheme#528]
Debian unstable and stretch (the next debian release) now ship with OpenSSL 1.1. Atheme fails to compile with that version of OpenSSL:

```
CompileModule: gcc -MMD -MP -g -O2 -fdebug-prefix-map=/tmp/buildd/atheme-services-7.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FORTIFY_SOURCE=2 -fPIC -DPIC -g -O2 -fdebug-prefix-map=/tmp/buildd/atheme-services-7.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FORTIFY_SOURCE=2  -std=gnu99 -Werror-implicit-function-declaration  -DPREFIX=\"/\" -DLOCALEDIR=\"/usr/share/locale\" -DMODDIR=\"//lib/x86_64-linux-gnu/atheme\" -DSHAREDIR=\"/usr/share/atheme\" -DSYSCONFDIR=\"/etc/atheme\" -DLOGDIR=\"/var/log/atheme\" -DRUNDIR=\"/var/run/atheme\" -DDATADIR=\"/var/lib/atheme\" -I/usr/include/libmowgli-2   -I../../include -shared -Wl,-z,relro -Wl,--as-needed -o pbkdf2.so pbkdf2.c -lcrypt    -lmowgli-2   -lssl -lcrypto -L../../libathemecore -lathemecore 
pbkdf2.c: In function 'PKCS5_PBKDF2_HMAC':
pbkdf2.c:47:11: error: storage size of 'hctx' isn't known
  HMAC_CTX hctx;
           ^~~~
pbkdf2.c:51:2: error: implicit declaration of function 'HMAC_CTX_init' [-Werror=implicit-function-declaration]
  HMAC_CTX_init(&hctx);
  ^~~~~~~~~~~~~
pbkdf2.c:87:2: error: implicit declaration of function 'HMAC_CTX_cleanup' [-Werror=implicit-function-declaration]
  HMAC_CTX_cleanup(&hctx);
  ^~~~~~~~~~~~~~~~
pbkdf2.c:47:11: warning: unused variable 'hctx' [-Wunused-variable]
  HMAC_CTX hctx;
           ^~~~
pbkdf2.c: In function 'pbkdf2_crypt':
pbkdf2.c:109:6: warning: variable 'res' set but not used [-Wunused-but-set-variable]
  int res, iter;
      ^~~
cc1: some warnings being treated as errors
../../buildsys.module.mk:15: recipe for target 'pbkdf2.so' failed
make[3]: *** [pbkdf2.so] Error 1
make[3]: Leaving directory '/tmp/buildd/atheme-services-7.2.7/modules/crypto'
../buildsys.mk:120: recipe for target 'crypto' failed
make[2]: *** [crypto] Error 2
make[2]: Leaving directory '/tmp/buildd/atheme-services-7.2.7/modules'
buildsys.mk:120: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/tmp/buildd/atheme-services-7.2.7'
```

This was first reported [in the Debian BTS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828241) where a full build log is also available.

**Comment by aaronmdjones** [comment]
The OpenSSL version that doesn't have PKCS5_PBKDF2_HMAC() is 0.9.8 and below; 1.0.0 and above have it, and both of those versions are End-Of-Life now, anyway.

The solution to this build error (for this specific compilation unit) is to simply remove the function.

**Comment by aaronmdjones** [comment]
(Please re-open this if you discover a compilation error in another file)

**Comment by anarcat** [comment]
same happens in v2:

```
CompileModule: gcc -MMD -MP -g -O2 -fdebug-prefix-map=/tmp/buildd/atheme-services-7.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FORTIFY_SOURCE=2 -fPIC -DPIC -g -O2 -fdebug-prefix-map=/tmp/buildd/atheme-services-7.2.7=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -D_FORTIFY_SOURCE=2  -std=gnu99 -Werror-implicit-function-declaration  -DPREFIX=\"/\" -DLOCALEDIR=\"/usr/share/locale\" -DMODDIR=\"//lib/x86_64-linux-gnu/atheme\" -DSHAREDIR=\"/usr/share/atheme\" -DSYSCONFDIR=\"/etc/atheme\" -DLOGDIR=\"/var/log/atheme\" -DRUNDIR=\"/var/run/atheme\" -DDATADIR=\"/var/lib/atheme\" -I/usr/include/libmowgli-2   -I../../include -shared -Wl,-z,relro -Wl,--as-needed -o pbkdf2v2.so pbkdf2v2.c -lcrypt    -lmowgli-2   -lssl -lcrypto -L../../libathemecore -lathemecore 
pbkdf2v2.c: In function 'PKCS5_PBKDF2_HMAC':
pbkdf2v2.c:73:11: error: storage size of 'hctx' isn't known
  HMAC_CTX hctx;
           ^~~~
pbkdf2v2.c:74:2: error: implicit declaration of function 'HMAC_CTX_init' [-Werror=implicit-function-declaration]
  HMAC_CTX_init(&hctx);
  ^~~~~~~~~~~~~
pbkdf2v2.c:105:2: error: implicit declaration of function 'HMAC_CTX_cleanup' [-Werror=implicit-function-declaration]
  HMAC_CTX_cleanup(&hctx);
  ^~~~~~~~~~~~~~~~
pbkdf2v2.c:73:11: warning: unused variable 'hctx' [-Wunused-variable]
  HMAC_CTX hctx;
           ^~~~
cc1: some warnings being treated as errors
../../buildsys.module.mk:15: recipe for target 'pbkdf2v2.so' failed
make[3]: *** [pbkdf2v2.so] Error 1
make[3]: Leaving directory '/tmp/buildd/atheme-services-7.2.7/modules/crypto'
../buildsys.mk:120: recipe for target 'crypto' failed
```

for some reason i can't reopen, no button?

**Comment by aaronmdjones** [comment]
It didn't even occur to me that the code would be in the version 2 module, heh.

**Comment by anarcat** [comment]
cool, looks like it's moving a little further now... so far so good. will let you know.

**Comment by anarcat** [comment]
looks good on the compile side, thanks!

**Comment by anarcat** [comment]
sigh, i just realized that debian *testing* still has OpenSSL 1.0 and it's not sure 1.1 will make it into the release considering how many packages are affected by such issues.

would the package still compile under 1.0 with the above changes? could we do some ifdef magic?

thanks.

**Comment by aaronmdjones** [comment]
The only version it will fail to compile under in the current state is 0.9.8, as explained above. The code in question should have been removed when that went EOL, but was overlooked. We don't need it.

**Comment by anarcat** [comment]
after testing, i can confirm that, sorry for the noise!
